project:
  type: website
  output-dir: docs
  
website:
  title: "Timothy P. Hofer, MD"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: projects.qmd
        text: Publications
    tools:
      - icon: bluesky
        href: https://bsky.app/profile/tim-hofer.bsky.social
      - icon: github
        href: https://github.com/tphofer/thofer
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2026, Timothy P. Hofer"

format:
  html:
    theme: cosmos
    toc: true

editor: source
